version: '3'

volumes:
  postgres_auth_microservices_data:
    driver: local

services:
  postgres-auth-microservice:
    image: postgres
    volumes:
      - postgres_auth_microservices_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
    networks:
      - my-network-auth-microservice
  pgadmin-auth-microservice:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: gustavoalvesandrade18@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5433:80
    depends_on:
      - postgres-auth-microservice
    networks:
      - my-network-auth-microservice
  keycloak-auth-microservice:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_SCHEMA: public
      DB_PASSWORD: $POSTGRES_PASSWORD
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: $KEYCLOAK_PASSWORD
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
      # ROOT_LOGLEVEL: DEBUG
      # KEYCLOAK_LOGLEVEL: DEBUG
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    depends_on:
      - postgres-auth-microservice
    networks:
      - my-network-auth-microservice
networks:
  my-network-auth-microservice:
    driver: bridge
