server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: resource-service
          uri: http://localhost:8083
          predicates:
            - Path=/resource/**
          filters:
            - RemoveRequestHeader=Cookie
